/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AImage: typeof import('ant-design-vue/es')['Image']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASpace: typeof import('ant-design-vue/es')['Space']
    Block: typeof import('./components/Block.vue')['default']
    CommonTitle: typeof import('./components/CommonTitle.vue')['default']
    copy: typeof import('./components/Block copy.vue')['default']
    DigitFlipper: typeof import('./components/DigitFlipper.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Number: typeof import('./components/Number.vue')['default']
    PDFViewer: typeof import('./components/PDFViewer.vue')['default']
    ResponseModal: typeof import('./components/ResponseModal.vue')['default']
    RightEvent: typeof import('./components/RightEvent.vue')['default']
    RightLight: typeof import('./components/RightLight.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoPlayer: typeof import('./components/VideoPlayer.vue')['default']
  }
}
